<?php

namespace App\Http\Controllers\PencariKos;

use App\Http\Controllers\Controller;
use App\Models\Pemesanan;
use App\Models\Kos;
use App\Models\Pembayaran;
use App\Http\Requests\PemesananRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class PemesananController extends Controller
{
    // List pemesanan milik pencari
    public function index()
    {
        $pemesanan = Pemesanan::with(['kos.pemilik', 'pembayaran'])
            ->where('pencari_id', Auth::id())
            ->latest()
            ->paginate(10);

        return view('pencari.pemesanan.index', compact('pemesanan'));
    }

    // Detail pemesanan
    public function show($id)
    {
        $pemesanan = Pemesanan::with(['kos.pemilik', 'pembayaran'])
            ->where('pencari_id', Auth::id())
            ->findOrFail($id);

        return view('pencari.pemesanan.show', compact('pemesanan'));
    }

    // Simpan pemesanan baru
    public function store(PemesananRequest $request)
    {
        $kos = Kos::findOrFail($request->kos_id);

        // Cek ketersediaan kamar
        if ($kos->kamar_tersedia < 1) {
            return back()->with('error', 'Maaf, kamar sudah penuh.');
        }

        // Hitung total harga
        $durasi = $request->durasi_sewa;
        $satuanDurasi = $request->satuan_durasi ?? 'bulan';
        
        // Convert to bulan for calculation
        $durasiBulan = $durasi;
        if ($satuanDurasi == 'tahun') {
            $durasiBulan = $durasi * 12;
        } elseif ($satuanDurasi == 'hari') {
            $durasiBulan = $durasi / 30;
        }
        
        $totalHarga = $kos->harga * $durasiBulan;

        // Create pemesanan (kode_pemesanan auto-generated by model boot)
        $pemesanan = Pemesanan::create([
            'kos_id' => $request->kos_id,
            'pencari_id' => Auth::id(),
            'tanggal_masuk' => $request->tanggal_masuk,
            'durasi_sewa' => $durasi,
            'satuan_durasi' => $satuanDurasi,
            'total_harga' => $totalHarga,
            'status' => 'pending',
            'catatan' => $request->catatan,
        ]);

        // Kirim notifikasi ke pemilik kos
        \App\Models\Notifikasi::kirim(
            $kos->pemilik_id,
            'Pemesanan Baru',
            "Anda mendapat pemesanan baru untuk {$kos->nama_kos} dari " . Auth::user()->nama,
            'info',
            route('pemilik.pemesanan.show', $pemesanan->id)
        );

        return redirect()->route('pencari.pemesanan.show', $pemesanan->id)
            ->with('success', 'Pemesanan berhasil dikirim! Menunggu persetujuan pemilik kos.');
    }

    // Upload bukti pembayaran
    public function uploadBuktiPembayaran(Request $request, $id)
    {
        $request->validate([
            'bukti_pembayaran' => 'required|image|mimes:jpeg,jpg,png|max:2048',
            'jumlah' => 'required|numeric|min:0',
        ], [
            'bukti_pembayaran.required' => 'Bukti pembayaran wajib diupload',
            'bukti_pembayaran.image' => 'File harus berupa gambar',
            'bukti_pembayaran.mimes' => 'Format file: JPG, JPEG, PNG',
            'bukti_pembayaran.max' => 'Ukuran maksimal 2MB',
            'jumlah.required' => 'Jumlah pembayaran wajib diisi',
        ]);

        $pemesanan = Pemesanan::where('pencari_id', Auth::id())
            ->findOrFail($id);

        // Check if status is disetujui
        if ($pemesanan->status !== 'disetujui') {
            return back()->with('error', 'Pemesanan belum disetujui oleh pemilik kos.');
        }

        // Upload bukti pembayaran
        $path = $request->file('bukti_pembayaran')->store('pembayaran', 'public');

        // Create pembayaran record
        $pembayaran = Pembayaran::create([
            'pemesanan_id' => $pemesanan->id,
            'jumlah' => $request->jumlah,
            'bukti_pembayaran' => $path,
            'status' => 'pending',
        ]);

        // Update status pemesanan
        $pemesanan->update([
            'status' => 'dibayar',
            'tanggal_dibayar' => now(),
        ]);

        // Kirim notifikasi ke pemilik kos
        \App\Models\Notifikasi::kirim(
            $pemesanan->kos->pemilik_id,
            'Bukti Pembayaran Diterima',
            "Bukti pembayaran untuk pemesanan {$pemesanan->kode_pemesanan} telah diupload. Silakan verifikasi.",
            'info',
            route('pemilik.pemesanan.show', $pemesanan->id)
        );

        return back()->with('success', 'Bukti pembayaran berhasil diupload. Menunggu verifikasi pemilik.');
    }

    // Batalkan pemesanan
    public function cancel($id)
    {
        $pemesanan = Pemesanan::where('pencari_id', Auth::id())
            ->findOrFail($id);

        // Only can cancel if status is pending or disetujui
        if (!in_array($pemesanan->status, ['pending', 'disetujui'])) {
            return back()->with('error', 'Pemesanan tidak dapat dibatalkan.');
        }

        $pemesanan->update([
            'status' => 'dibatalkan',
        ]);

        return back()->with('success', 'Pemesanan berhasil dibatalkan.');
    }
}
